INSERT INTO Team VALUES ('Spain',6);
INSERT INTO Team VALUES ('England',4);
INSERT INTO Team VALUES ('Australia',10);
INSERT INTO Team VALUES ('Switzerland',22);
INSERT INTO Team VALUES ('Korea Republic',20);
INSERT INTO Team VALUES ('Germany',5);
INSERT INTO Team VALUES ('United States',1);
INSERT INTO Team VALUES ('Netherlands',9);
INSERT INTO Team VALUES ('Norway',12);
INSERT INTO Team VALUES ('Japan',8);
INSERT INTO Team VALUES ('Brazil',9);
INSERT INTO Team VALUES ('Canada',7);
INSERT INTO Team VALUES ('France',5);
INSERT INTO Team VALUES ('Republic Of Ireland',22);
INSERT INTO Team VALUES ('Nigeria',40);
INSERT INTO Team VALUES ('Sweden',2);
INSERT INTO Team VALUES ('China',15);
INSERT INTO Team VALUES ('Argentina',31);
INSERT INTO Team VALUES ('Colombia',25);
INSERT INTO Team VALUES ('Costa Rica',37);
INSERT INTO Team VALUES ('Denmark',12);
INSERT INTO Team VALUES ('Hait',53);
INSERT INTO Team VALUES ('Italy',16);
INSERT INTO Team VALUES ('Jamaica',43);
INSERT INTO Team VALUES ('Morocco',72);
INSERT INTO Team VALUES ('New Zealand',26);
INSERT INTO Team VALUES ('Zambia',77);
INSERT INTO Team VALUES ('Panama',56);
INSERT INTO Team VALUES ('Philippines',46);
INSERT INTO Team VALUES ('Portugal',32);
INSERT INTO Team VALUES ('Vietnam',32);
INSERT INTO Team VALUES ('Cameroon',52);
INSERT INTO Team VALUES ('South Africa',56);
INSERT INTO Team VALUES ('Chile',41);
INSERT INTO Team VALUES ('scotland',22);
INSERT INTO Team VALUES ('Thailand',44);
INSERT INTO Team VALUES ('Ivory Coast',66);
INSERT INTO Team VALUES ('ecuador',null);
INSERT INTO Team VALUES ('Mexico',35);
INSERT INTO Team VALUES ('Equ. Guinea',null);
INSERT INTO Team VALUES ('Ghana',58);
INSERT INTO Team VALUES ('Korea DPR',null);
INSERT INTO Team VALUES ('Russia',24);
INSERT INTO Team VALUES ('Chinese Taipei',null);

